BotSelfConfig:
  host: "127.0.0.1"
  port: 25565
  debug: false
  superusers: ["1234567890"]
  nickname: ["ATRI", "Atri", "atri", "亚托莉", "アトリ"]
  command_start: ["", "/"]
  command_sep: ["."]
  session_expire_timeout: 120
  session_exciting_time: 3

NetworkPost:
  host: "127.0.0.1"
  port: 23333

AdminPage:
  host: "127.0.0.1"
  port: 11451
