BotSelfConfig:
  host: "127.0.0.1"
  port: 8080
  debug: true
  superusers: ["1234567890"]
  nickname: ["ATRI", "Atri", "atri", "亚托莉", "アトリ"]
  command_start: ["", "/"]
  command_sep: ["."]
  session_expire_timeout: 3
  session_exciting_time: 3

HttpPost:
  host: "127.0.0.1"
  port: 8081